# Generated by Django 4.1 on 2022-09-28 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=270)),
                ('subtitulo', models.CharField(max_length=200)),
                ('texto', models.TextField(max_length=2700)),
                ('autor', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_posts')),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
