# Generated by Django 4.1 on 2022-09-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_autor_post_username_alter_post_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='img',
        ),
    ]
