# Generated by Django 4.1 on 2022-09-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_imagen_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=50, null=True)),
                ('receptor', models.CharField(max_length=50, null=True)),
                ('mensaje', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
